version: "3.9"

services:
  db:
    image: nouchka/sqlite3:latest
    volumes:
      - db_data:/myapp/db

  api:
    tty: true
    stdin_open: true
    build: .
    command: rails server -b 0.0.0.0
    volumes:
      - ".:/myapp"
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=sqlite3://db/development.sqlite3
    #env_file: .env

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    depends_on:
      - db_sonarqube
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonarqube

    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_plugins:/opt/sonarqube/lib/bundled-plugins
      - /usr/src/app:/src

  db_sonarqube:
    image: postgres:latest
    container_name: postgres_sonarqube
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonarqube
    volumes:
      - postgres_sonarqube_data:/var/lib/postgresql/data

volumes:
  db_data:
  sonarqube_data:
  sonarqube_conf:
  sonarqube_extensions:
  sonarqube_plugins:
  postgres_sonarqube_data:

